---
- name: Setup nodes
  hosts: all
  become: true
  vars:
    internal_interface: 'eth1'
  tasks:
  - name: Set hostname to {{ inventory_hostname }}
    hostname:
      name: "{{ inventory_hostname }}"
  - name: Build /etc/hosts file
    ansible.builtin.blockinfile:
      create: true
      path: /etc/hosts
      block: |
          {% for host in groups['all'] %}
          {{ hostvars[host]['ansible_facts'][internal_interface]['ipv4']['address'] }} {{ host }}
          {% endfor %}
  - name: Build inventory hosts
    delegate_to: localhost
    become: false
    ansible.builtin.blockinfile:
      create: true
      path: "{{ playbook_dir }}/hosts"
      block: |
          [controller]
          {% for host in groups['all'] %}
          {% if "controller" in host %}
          {{ host }} ansible_host={{ hostvars[host]['ansible_facts'][internal_interface]['ipv4']['address'] | default( hostvars[host]['ansible_ssh_host'] ) }} ansible_user={{ deploy_user }}
          {% endif %}
          {% endfor %}

          [worker]
          {% for host in groups['all'] %}
          {% if "worker" in host %}
          {{ host }} ansible_host={{ hostvars[host]['ansible_facts'][internal_interface]['ipv4']['address'] | default( hostvars[host]['ansible_ssh_host'] ) }} ansible_user={{ deploy_user }}
          {% endif %}
          {% endfor %}

          [loadbalancer]
          {% for host in groups['all'] %}
          {% if "loadbalancer" in host %}
          {{ host }} ansible_host={{ hostvars[host]['ansible_facts'][internal_interface]['ipv4']['address'] | default( hostvars[host]['ansible_ssh_host'] ) }} ansible_user={{ deploy_user }}
          {% endif %}
          {% endfor %}
  - name: Disable swap permanently
    ansible.builtin.systemd:
      service: swap.target
      masked: true
    register: mask_swap
  - name: Disable swap
    shell: swapoff -a
    when: mask_swap.changed
