---
- name: Generating the Data Encryption Key and Config
  hosts: controller[0]
  tasks:
  - name: Get Encryption Config Stats
    stat:
      path: "{{ data_dir }}/encryption-config.yaml"
    register: encconfig

  - name: The Encryption Config File
    ansible.builtin.template:
      src: encryption-config.yaml.j2
      dest: "{{ data_dir }}/encryption-config.yaml"
    when: not encconfig.stat.exists

- name: Encryption Config
  hosts: controller
  user: ansible
  gather_facts: False
  tasks:

  - name: Slurp Encryption Config
    delegate_to: "{{ groups['controller'] | first }}"
    slurp:
      src: "{{ data_dir }}/encryption-config.yaml"
    register: encconfig_content

  - debug:
      msg: "{{ encconfig_content.content | b64decode }}"

  - name: Copy Encryption Config
    copy:
      dest: "{{ data_dir }}/encryption-config.yaml"
      content: "{{ encconfig_content.content | b64decode }}"
